### ISSUE TITLE
Fit content

### ISSUE THREAD

**Issue by gogui63** [KaoruKanon/homeassistant-config#1]
Salut, merci pour ta partage du thème de Matt en version FR. 
Ca faisait un moment que je regardais et j'ai enfin pu trouver un peu de temps pour refaire un Dashboard similaire mais je rencontre un petit soucis d'affichage : 

![image](https://user-images.githubusercontent.com/5662539/135806592-9ff5cd5b-5019-4d69-b24a-ebbeeb89ed65.png)

Mes cards ne rentrent pas dans l'écran dans le sens ou je dois scroller pour voir le footer et la fin de la deuxième ligne. Au niveau css pourtant ca semble OK quand j'inspecte le body semble bien être de la taille de l'écran.. 
Autant sur la partie scripting, automation, template, aucun soucis. Autant partie CSS pas mon domaine du tout 😄 

Aurais tu une idée du paramètre à changer, ou peut etre j'ai zappé qq chose ?

**Comment by KaoruKanon** [comment]
Bonjour,

En pleine fenêtre sur pc, le theme fit pas très bien malgré le reponsive qui est une fonctionnalité récente. 

J'imagine que tu utilises la dernière version du thème ?

**Comment by gogui63** [comment]
Yes dernière version, ton dernier commit. Même en mode non kiosk ça ne fit pas , ça déborde. Je vois pas trop où est le soucis ? Dans le thème ? Dans le bouton card layout ? 
Je vois pas où creuser

**Comment by KaoruKanon** [comment]
Tiens voici le comportement que me fait le thème. Comme tu peux le voir quand t'es en pleine fenêtre sur ton écran, ça passe pas bien tout comme en fullscreen sur chrome d'ailleurs. Tu dois redimensionner en plus petit pour que ça fit correctement

https://user-images.githubusercontent.com/40307380/135918983-cfd6d193-b626-4f87-85c2-4085a9a8e17d.mp4

Je t'avouerai quand je contrôle ma domotique sur mon pc, j'utilise ma web app et pas depuis un navigateur classique. J'ai un raccourci sur windows et en plus c'est accessible sur mon streamdeck. Ce que je te propose, c'est [applicationize ](https://applicationize.me/now), ça règle ce problème.

![applicationize](https://user-images.githubusercontent.com/40307380/135919368-fc7f7062-75c9-41c2-9841-1312ffc96229.JPG)

C'est facile. Tu donnes ton l'url dedans https://domain.tld/lovelace/default?kiosk
ça te génère l'extension et tu as juste à l'installer en mode dev dans les extension de chrome. C'est expliqué sur le site en anglais avec des photos. Tu peux mettre un logo quand tu lances l'app depuis windows, etc depuis les advanced options.

Par contre certaines choses à savoir : 
* Quand tu vas lancer ton app, tu vas te logger sur ton HA mais directement tu vas rester bloquer sur lovelace sans pouvoir changer le thème d'HA. Tu dois spamer les ouvertures et fermeture de la web app pour ouvrir le menu de ton profil quand la barre lattéral d'HA apparait pendant un court instant. ça reste jouable 
* La seconde chose à faire, c'est de changer la taille de la fenêtre pour fit correctement. Normalement quand c'est fait, quand tu relances ta web app, ça te fait un truc propre avec le bon fit. ça arrive que ça saute de temps en temps

**Comment by gogui63** [comment]
Effectivement tu as raison c'est pas encore carré :) 

En passant via l'app desktop et en jouant un peu sur la taille de la fenêtre ca finit par fit, à voir sur ma tablette car c'est ca la cible. 
Je n'utilise que rarement en actionneur mon HA , ma tablette ne me sert que pour de la visualisation et tout le reste se fait via la voix / automation 

En tout cas merci pour tes réponses détaillées ! 
Je vais suivre tes commits de près, en espérant que ca s'ameliore  😄

**Comment by KaoruKanon** [comment]
En tout cas sur tablette avec Fullykiosk en ratio 16/9, ça marche directement 

Moi, je suis bien content du responsive surtout pour l'utilisation téléphone mais y a encore quelques problèmes qui ne sont pas du ressort de matt. (notamment les swipe-card qui change de taille)

Merci, ça évoluera encore un peu mais j'ai fait le plus gros 😉

Je ferme l'issue !
